# Generated by Django 5.0 on 2025-10-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='מפתח סשן')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'סל קניות',
                'verbose_name_plural': 'סלי קניות',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הוספה')),
            ],
            options={
                'verbose_name': 'פריט בסל',
                'verbose_name_plural': 'פריטים בסל',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='שם קטגוריה')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='סלאג')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='תמונה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'קטגוריה',
                'verbose_name_plural': 'קטגוריות',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל אורח')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון אורח')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='שם אורח')),
                ('guest_address', models.CharField(blank=True, max_length=255, verbose_name='כתובת אורח')),
                ('guest_city', models.CharField(blank=True, max_length=100, verbose_name='עיר אורח')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום כולל')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('confirmed', 'אושר'), ('shipped', 'נשלח'), ('delivered', 'נמסר'), ('cancelled', 'בוטל')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'הזמנה',
                'verbose_name_plural': 'הזמנות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר')),
            ],
            options={
                'verbose_name': 'פריט בהזמנה',
                'verbose_name_plural': 'פריטים בהזמנה',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם מוצר')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='סלאג')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='כמות במחסן')),
                ('image', models.ImageField(upload_to='products/', verbose_name='תמונה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('is_featured', models.BooleanField(default=False, verbose_name='מוצר מומלץ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
                'ordering': ['-created_at'],
            },
        ),
    ]
