# Generated by Django 5.0 on 2025-10-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='בוטיק אריה', max_length=200, verbose_name='שם האתר')),
                ('hero_banner', models.ImageField(upload_to='banners/', verbose_name='באנר ראשי')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='כותרת באנר')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='תת-כותרת באנר')),
                ('is_active', models.BooleanField(default=True, verbose_name='באנר פעיל')),
            ],
            options={
                'verbose_name': 'הגדרות אתר',
                'verbose_name_plural': 'הגדרות אתר',
            },
        ),
    ]
