# Generated by Django 5.0 on 2025-11-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=200, verbose_name='גודל'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='תמונה')),
                ('is_primary', models.BooleanField(default=False, verbose_name='תמונה ראשית')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'תמונת מוצר',
                'verbose_name_plural': 'תמונות מוצר',
                'ordering': ['-is_primary', 'order', 'created_at'],
            },
        ),
    ]
