# Generated by Django 5.0 on 2025-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_size_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('boy', 'בן'), ('girl', 'בת'), ('both', 'שניהם')], default='both', max_length=10, verbose_name='מין'),
        ),
    ]
