# Generated by Django 5.0 on 2025-11-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_parent_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='שם קטגוריה'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='סלאג'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='קטגוריה'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם תת-קטגוריה')),
                ('slug', models.SlugField(max_length=200, verbose_name='סלאג')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('image', models.ImageField(blank=True, upload_to='subcategories/', verbose_name='תמונה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category', verbose_name='קטגוריה')),
            ],
            options={
                'verbose_name': 'תת-קטגוריה',
                'verbose_name_plural': 'תת-קטגוריות',
                'ordering': ['name'],
                'unique_together': {('slug', 'category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.subcategory', verbose_name='תת-קטגוריה'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
