# Generated by Django 5.0 on 2025-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_unique_together_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='שם מלא')),
                ('phone', models.CharField(max_length=20, verbose_name='טלפון')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='מספר הזמנה')),
                ('inquiry', models.TextField(verbose_name='מהות הפנייה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('is_read', models.BooleanField(default=False, verbose_name='נקרא')),
            ],
            options={
                'verbose_name': 'הודעת צור קשר',
                'verbose_name_plural': 'הודעות צור קשר',
                'ordering': ['-created_at'],
            },
        ),
    ]
