# Generated by Django 5.2.4 on 2025-11-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelowBestsellersGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_image', models.ImageField(upload_to='gallery/', verbose_name='תמונה ימנית')),
                ('left_image', models.ImageField(upload_to='gallery/', verbose_name='תמונה שמאלית')),
                ('is_active', models.BooleanField(default=True, verbose_name='גלריה פעילה')),
            ],
            options={
                'verbose_name': 'גלריה מתחת להכי נמכרים',
                'verbose_name_plural': 'גלריה מתחת להכי נמכרים',
            },
        ),
    ]
