# Generated by Django 5.2.4 on 2025-11-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_belowbestsellersgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='ציטוט/המלצה')),
                ('author', models.CharField(max_length=100, verbose_name='שם הממליץ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'המלצת לקוח',
                'verbose_name_plural': 'המלצות לקוחות',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
