# Generated by Django 5.2.4 on 2025-11-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(max_length=100, verbose_name='שם המליץ'),
        ),
    ]
