# Generated by Django 5.2.4 on 2025-11-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_testimonial_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='instagram/', verbose_name='תמונה 1')),
                ('image_2', models.ImageField(upload_to='instagram/', verbose_name='תמונה 2')),
                ('image_3', models.ImageField(upload_to='instagram/', verbose_name='תמונה 3')),
                ('instagram_url', models.URLField(help_text='קישור לפרופיל האינסטגרם של החברה', max_length=500, verbose_name='קישור לאינסטגרם')),
                ('is_active', models.BooleanField(default=True, verbose_name='גלריה פעילה')),
            ],
            options={
                'verbose_name': 'גלריית אינסטגרם',
                'verbose_name_plural': 'גלריית אינסטגרם',
            },
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.CharField(max_length=100, verbose_name='שם הממליץ'),
        ),
    ]
