# Generated by Django 5.2.4 on 2025-11-19 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_instagramgallery_alter_testimonial_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='סוג בד')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_types', to='store.product', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'סוג בד',
                'verbose_name_plural': 'סוגי בד',
                'ordering': ['order', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='מידה')),
                ('is_available', models.BooleanField(default=True, verbose_name='זמין')),
                ('warehouse_location', models.CharField(blank=True, help_text='למשל: A12, B05, C23', max_length=50, verbose_name='מיקום תא במחסן')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.fabrictype', verbose_name='סוג בד')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'וריאנט מוצר',
                'verbose_name_plural': 'וריאנטים של מוצרים',
                'ordering': ['fabric_type__order', 'size'],
                'unique_together': {('product', 'fabric_type', 'size')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='store.productvariant', verbose_name='וריאנט'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.productvariant', verbose_name='וריאנט'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
    ]
