# Generated by Django 5.2.4 on 2025-11-20 06:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_fabrictype_productvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם מידה')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='סלאג')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='שם מלא לתצוגה')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'מידה',
                'verbose_name_plural': 'מידות',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['fabric_type__order', 'size__order'], 'verbose_name': 'וריאנט מוצר', 'verbose_name_plural': 'וריאנטים של מוצרים'},
        ),
        migrations.AlterUniqueTogether(
            name='fabrictype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך יצירה'),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='פעיל'),
        ),
        migrations.AlterField(
            model_name='fabrictype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='סוג בד'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='fabric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='store.fabrictype', verbose_name='סוג בד'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='store.size', verbose_name='מידה'),
        ),
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם קבוצה')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='סלאג')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך יצירה')),
                ('sizes', models.ManyToManyField(help_text='בחר את המידות שנכללות בקבוצה זו', related_name='size_groups', to='store.size', verbose_name='מידות')),
            ],
            options={
                'verbose_name': 'קבוצת מידות',
                'verbose_name_plural': 'קבוצות מידות',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='fabrictype',
            name='product',
        ),
    ]
