# Generated by Django 5.2.4 on 2025-11-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_update_fabric_and_size_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabrictype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה'),
        ),
        migrations.AlterField(
            model_name='size',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה'),
        ),
        migrations.AlterField(
            model_name='sizegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה'),
        ),
    ]
