# Generated by Django 5.2.4 on 2025-11-20 08:59

from django.db import migrations
from django.utils.text import slugify


def add_initial_sizes(apps, schema_editor):
    """הוספת מידות ראשוניות"""
    Size = apps.get_model('store', 'Size')
    
    # מידות לתינוקות (בחודשים)
    baby_sizes = [
        ('0-3', '0-3 חודשים', 1),
        ('3-6', '3-6 חודשים', 2),
        ('6-12', '6-12 חודשים', 3),
        ('12-18', '12-18 חודשים', 4),
        ('18-24', '18-24 חודשים', 5),
    ]
    
    # מידות לילדים (במספרים)
    kid_sizes = [
        ('2', 'מידה 2', 6),
        ('4', 'מידה 4', 7),
        ('5', 'מידה 5', 8),
        ('6', 'מידה 6', 9),
        ('8', 'מידה 8', 10),
        ('10', 'מידה 10', 11),
        ('12', 'מידה 12', 12),
        ('14', 'מידה 14', 13),
        ('16', 'מידה 16', 14),
    ]
    
    all_sizes = baby_sizes + kid_sizes
    
    for name, display_name, order in all_sizes:
        Size.objects.get_or_create(
            name=name,
            defaults={
                'slug': slugify(name, allow_unicode=True),
                'display_name': display_name,
                'order': order,
                'is_active': True,
            }
        )


def add_initial_size_groups(apps, schema_editor):
    """הוספת קבוצות מידות ראשוניות"""
    Size = apps.get_model('store', 'Size')
    SizeGroup = apps.get_model('store', 'SizeGroup')
    
    # קבוצה 1: תינוק שנולד
    newborn_group, created = SizeGroup.objects.get_or_create(
        name='תינוק שנולד',
        defaults={
            'slug': slugify('תינוק שנולד', allow_unicode=True),
            'order': 1,
            'is_active': True,
        }
    )
    if created:
        size_0_3 = Size.objects.filter(name='0-3').first()
        if size_0_3:
            newborn_group.sizes.add(size_0_3)
    
    # קבוצה 2: בגדי גוף
    bodysuits_group, created = SizeGroup.objects.get_or_create(
        name='בגדי גוף',
        defaults={
            'slug': slugify('בגדי גוף', allow_unicode=True),
            'order': 2,
            'is_active': True,
        }
    )
    if created:
        # הוספת כל מידות התינוקות
        baby_sizes = Size.objects.filter(name__in=['0-3', '3-6', '6-12', '12-18', '18-24'])
        bodysuits_group.sizes.add(*baby_sizes)


def remove_initial_data(apps, schema_editor):
    """הסרת נתונים ראשוניים במקרה של rollback"""
    Size = apps.get_model('store', 'Size')
    SizeGroup = apps.get_model('store', 'SizeGroup')
    
    # מחיקת קבוצות
    SizeGroup.objects.filter(name__in=['תינוק שנולד', 'בגדי גוף']).delete()
    
    # מחיקת מידות (רק אם אין להן וריאנטים קשורים)
    size_names = ['0-3', '3-6', '6-12', '12-18', '18-24', '2', '4', '5', '6', '8', '10', '12', '14', '16']
    for size_name in size_names:
        Size.objects.filter(name=size_name, variants__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_fabrictype_created_at_alter_size_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_sizes, remove_initial_data),
        migrations.RunPython(add_initial_size_groups, migrations.RunPython.noop),
    ]
