# Generated by Django 5.0 on 2025-12-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_add_initial_sizes_and_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(help_text='תמונה לבאנר בראש דף האודות', upload_to='about/', verbose_name='תמונת באנר ראשי')),
                ('content_image_1', models.ImageField(help_text='תמונה לסקשן אריה (משמאל)', upload_to='about/', verbose_name='תמונה 1 - אריה')),
                ('content_image_2', models.ImageField(help_text='תמונה לסקשן אריה בוטיק (מימין)', upload_to='about/', verbose_name='תמונה 2 - אריה בוטיק')),
                ('content_image_3', models.ImageField(help_text='תמונה לסקשן הייחוד שלנו (משמאל)', upload_to='about/', verbose_name='תמונה 3 - הייחוד שלנו')),
                ('content_image_4', models.ImageField(help_text='תמונה לסקשן האיכות שלנו (מימין)', upload_to='about/', verbose_name='תמונה 4 - האיכות שלנו')),
                ('is_active', models.BooleanField(default=True, verbose_name='הגדרות פעילות')),
            ],
            options={
                'verbose_name': 'הגדרות דף אודות',
                'verbose_name_plural': 'הגדרות דף אודות',
            },
        ),
    ]
