# Generated by Django 5.0 on 2025-12-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_aboutpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleriesHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'גלריות',
                'verbose_name_plural': 'גלריות',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='שאלה')),
                ('answer', models.TextField(verbose_name='תשובה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('order', models.IntegerField(default=0, verbose_name='סדר תצוגה')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'שאלה ותשובה',
                'verbose_name_plural': 'שאלות ותשובות',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpagesettings',
            options={'verbose_name': 'גלריות - הגדרות דף אודות', 'verbose_name_plural': 'גלריות - הגדרות דף אודות'},
        ),
        migrations.AlterModelOptions(
            name='belowbestsellersgallery',
            options={'verbose_name': 'גלריות - גלריה מתחת להכי נמכרים', 'verbose_name_plural': 'גלריות - גלריה מתחת להכי נמכרים'},
        ),
        migrations.AlterModelOptions(
            name='instagramgallery',
            options={'verbose_name': 'גלריות - גלריית אינסטגרם', 'verbose_name_plural': 'גלריות - גלריית אינסטגרם'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'גלריות - גלריה ראשית', 'verbose_name_plural': 'גלריות - גלריה ראשית'},
        ),
    ]
