# Generated by Django 5.2.4 on 2025-12-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_gallerieshub_faq_alter_aboutpagesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם החנות')),
                ('logo', models.ImageField(upload_to='retailers/', verbose_name='לוגו החנות')),
                ('website_url', models.URLField(blank=True, help_text='אופציונלי - קישור לאתר החנות', max_length=500, null=True, verbose_name='קישור לאתר')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'גלריות - חנות משווקת',
                'verbose_name_plural': 'גלריות - חנויות משווקות',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
