# Generated by Django 5.0 on 2025-12-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_retailerstore_delete_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת')),
                ('subtitle', models.CharField(help_text='תיאור קצר שיופיע מתחת לכותרת', max_length=300, verbose_name='תת-כותרת')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='תמונה ראשית')),
                ('content', models.TextField(verbose_name='תוכן הפוסט')),
                ('slug', models.SlugField(help_text='יופיע בכתובת הדף (באנגלית, ללא רווחים)', max_length=200, unique=True, verbose_name='כתובת URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
            ],
            options={
                'verbose_name': 'פוסט בבלוג',
                'verbose_name_plural': 'פוסטים בבלוג',
                'ordering': ['-created_at'],
            },
        ),
    ]
