# Generated by Django 5.0 on 2025-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='תת כותרת'),
        ),
    ]
