# Generated by Django 5.2.4 on 2025-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramgallery',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='instagram/', verbose_name='תמונה 4'),
        ),
    ]
