# Generated by Django 5.0 on 2025-12-23 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_instagramgallery_image_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='blog/', verbose_name='תמונת באנר ראשי'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='כותרת ראשית'),
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('title', models.CharField(max_length=200, verbose_name='כותרת הסקשן')),
                ('content', models.TextField(verbose_name='תוכן/פיסקה')),
                ('image', models.ImageField(blank=True, help_text='תמונה אופציונלית לסקשן', null=True, upload_to='blog/sections/', verbose_name='תמונה')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='store.blogpost', verbose_name='פוסט')),
            ],
            options={
                'verbose_name': 'סקשן בפוסט',
                'verbose_name_plural': 'סקשנים בפוסט',
                'ordering': ['order'],
            },
        ),
    ]
