# Generated by Django 5.0 on 2025-12-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_blogpost_content_remove_blogpost_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='שם מזהה')),
                ('description', models.TextField(verbose_name='תיאור הרכב חומרים וטיפול')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'הרכב חומרים וטיפול',
                'verbose_name_plural': 'הרכב חומרים וטיפול',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='material_care_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.materialcareinfo', verbose_name='הרכב חומרים וטיפול'),
        ),
    ]
