# Generated by Django 5.0 on 2025-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_materialcareinfo_product_material_care_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'מוצר', 'verbose_name_plural': 'מוצרים'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה'),
        ),
    ]
