# Generated by Django 5.0 on 2026-01-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_options_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='כתובת אימייל')),
                ('coupon_code', models.CharField(max_length=20, unique=True, verbose_name='קוד קופון')),
                ('discount_percent', models.IntegerField(default=10, verbose_name='אחוז הנחה')),
                ('is_used', models.BooleanField(default=False, verbose_name='קופון נוצל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך הרשמה')),
            ],
            options={
                'verbose_name': 'מנוי ניוזלטר',
                'verbose_name_plural': 'מנויי ניוזלטר',
                'ordering': ['-created_at'],
            },
        ),
    ]
