# Generated by Django 5.0 on 2026-01-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='מנוי פעיל'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='טוקן ביטול הרשמה'),
        ),
    ]
