# Generated by Django 5.0 on 2026-01-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_newslettersubscriber_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='קוד קופון')),
                ('discount_type', models.CharField(choices=[('percent', 'אחוזים'), ('fixed', 'סכום קבוע')], default='percent', max_length=10, verbose_name='סוג הנחה')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='אחוזים (לדוגמה: 10) או סכום קבוע בש"ח', max_digits=10, verbose_name='ערך הנחה')),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='0 = ללא מינימום', max_digits=10, verbose_name='סכום מינימום להזמנה')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = ללא הגבלה', verbose_name='מספר שימושים מקסימלי')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='מספר פעמים שנוצל')),
                ('valid_from', models.DateTimeField(verbose_name='תקף מתאריך')),
                ('valid_until', models.DateTimeField(verbose_name='תקף עד תאריך')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך יצירה')),
            ],
            options={
                'verbose_name': 'קופון',
                'verbose_name_plural': 'קופונים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='קוד קופון'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='סכום הנחה'),
        ),
    ]
