# Generated by Django 5.0 on 2026-01-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_coupon_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='coming_soon_enabled',
            field=models.BooleanField(default=False, verbose_name='הפעל דף Coming Soon'),
        ),
    ]
