# Generated by Django 5.0 on 2026-01-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_sitesettings_coming_soon_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='מזהה תשלום'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין לתשלום'), ('paid', 'שולם'), ('confirmed', 'אושר'), ('shipped', 'נשלח'), ('delivered', 'נמסר'), ('cancelled', 'בוטל')], default='pending', max_length=20, verbose_name='סטטוס'),
        ),
    ]
