# Generated by Django 5.0 on 2026-01-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_order_payment_reference_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='תאריך תשלום'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='טוקן תשלום'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='מזהה עסקה'),
        ),
    ]
