# Generated by Django 5.0 on 2026-02-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_order_paid_at_order_payment_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_label',
            field=models.CharField(default='מידה', help_text='למשל: "מידה" לבגדים, "סוג" לסדינים', max_length=50, verbose_name='תווית מידה'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='השאר ריק לשימוש במחיר המוצר הרגיל', max_digits=10, null=True, verbose_name='מחיר מותאם'),
        ),
    ]
