# Generated by Django 5.0 on 2026-02-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_variant_price_override_and_size_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['size__order'], 'verbose_name': 'וריאנט מוצר', 'verbose_name_plural': 'וריאנטים של מוצרים'},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='store.fabrictype', verbose_name='סוג בד'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('fabric_type__isnull', True)), fields=('product', 'size'), name='store_productvariant_unique_product_size_no_fabric'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('fabric_type__isnull', False)), fields=('product', 'fabric_type', 'size'), name='store_productvariant_unique_product_fabric_size'),
        ),
    ]
