# Generated by Django 5.0 on 2026-03-17 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_optional_fabric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='demo_token',
            field=models.UUIDField(default=uuid.uuid4, help_text='שלח קישור עם ?demo=TOKEN כדי לאפשר גלישה בלי רכישה', verbose_name='טוקן דמו'),
        ),
    ]
